* java-getopt

** Background
The original author of =java-getopt= is Aaron M. Renn.  I have forked his
work, applied a bunch of pull-requests that were open in his repoistory,
and added / removed things based on what I wanted, like using Gradle instead
of Make, etc.

** Introduction (verbatim from the original)
 This is a Java port of the GNU getopt functions based on the versions 
 contained in glibc 2.0.6.  I have attempted to keep the functionality 
 and programmer's interface as faithful to the original as possible.
 However, due to differences between Java and C, some minor changes
 has to me made.  (Given the obtuse interface in the clib version, 
 perhaps some major changes should have been made).  This should not 
 affect the way options appear to be parsed to the end user of program 
 that uses this Java getopt.  The use of these classes are completely 
 documented in the javadoc comments, so I will not repeat that info here. 

 Note that since these objects are part of a package called "gnu.getopt", 
 they need to be in a subdirectory called gnu/getopt somewhere in your 
 CLASSPATH.  This includes the "MessagesBundle" files.

** Bugs
 The original author is not aware of any bugs.  If you find one though, 
 please open an issue on Github.  This will allow me to track it and have
 a record of it.  The more detailed a bug report the better.  Bug fixes 
 are also welcome at the same address.

** How to build
To build the project just run:
\\
#+BEGIN_SRC shell
./gradlew build javadoc
#+END_SRC
\\
This will create the JAR file in =build/libs=, class files in =build/classes/main/gnu/getopt= and
the documentation in =build/docs/javadoc=.  

 There is sample code showing how to use =getopt= available in the
 =src/main/java/GetoptDemo.java= file.



Mehul
     
-----
Original README was written by

Aaron. \\
arenn@urbanophile.com \\
http://www.urbanophile.com/arenn/
